### ISSUE TITLE
Metahandlers issue

### ISSUE THREAD

**Issue by thwaller** [tknorris/1Channel#14]
Please see here:
https://github.com/Eldorados/script.module.metahandler/issues/2

How can this be fixed?

**Comment by tknorris** [comment]
I don't want to add this to 1CH. I think the metahandler settings should be updated to allow adding your own key.

**Comment by tknorris** [comment]
Also, if you just do @tknorris, it will notify me, you don't have to do a whole new issues.

**Comment by thwaller** [comment]
Thanks for the note in the last statement, I was unaware of that. :)
