### ISSUE TITLE
Unaired episodes

### ISSUE THREAD

**Issue by thwaller** [tknorris/1Channel#16]
Is there a way to add/remove unaired episodes and/or season 0 episodes as in SALTS? I have a few strange issues which TVDB and TMDB disagree on, the listing of episodes and what is/is not included. It is causing 1channel to improperly list the questionable episodes. I would rather just have then excluded and manually view them elsewhere where the data providers don't mess things up.

In a specific example for clarification purposes....there are 4 episodes that complete season 1 that were never aired in the US by NBC. These 4 episodes were not aired to to series cancellation. These 4 episodes were aired in UK and are available on the DVD. Now given this, TMDB/etc show them as episodes with air dates, this data is correct. TVDB states that they are not "aired" as the official country is US, and US did not air them. So... stream providers have them there, but if the data is not pulled correctly, I am sure you can see the issue on those last 4 episodes.

**Comment by tknorris** [comment]
Do you mean from the library or from inside SALTS itself?

**Comment by thwaller** [comment]
In the settings, SALTS has the option to include / excluse unaired and season 0 material. 1Channel does not have such option unless I have missed it. I am on the beta repository for both 1channel and SALTS. Any solution to resolve the issue would work really, I do not see TVDB doing anything as they have all the answers.

**Comment by tknorris** [comment]
Oh, I misunderstood your questoin. I thought you were asking hwo to not show them in SALTS. No, there's no way to remove them from 1CH. 1CH just always shows what the PW site has.

**Comment by thwaller** [comment]
Hmmm, I will check the PW site, but the data pulled shows the 4 episodes in question, but they are completely wrong.

**Comment by thwaller** [comment]
Ok, I checked PW, they have the listing correct. Now the issue appears to be then how the sources end up in Kodi. Thoughts on this? The listing in Kodi via linbrary does not match what is displayed within PW website.

**Comment by tknorris** [comment]
Once you pull the data in to Kodi, then TVDB scraper kicks in, which is why it gets weird. If you view the episodes in 1CH itself, it'll match PW (as long as you have metahandler turned off which also pulls from TVDB)

**Comment by thwaller** [comment]
I see. I will look at that. Thanks for the input. This closes the issue as it is not 1Channel, but TVDB.
