### ISSUE TITLE
Abnormal episodes

### ISSUE THREAD

**Issue by thwaller** [tknorris/1Channel#17]
Is there a way to prevent the subscription option on 1Channel from pulling in episode data that is not "valid"? Meaning, things like S01E102 (there is obviously no episode 102), etc? I can provide very specific details if it helps, but in general...

I am using Kodi, 1Channel addon and add tv shows to the Kodi library with subscription, with ended shows set to be cleaned up. I use MediaElch to manage and create local nfo for library data. As this information pulled in from 1Channel does not have an episode to match up to, there is always notice and deleting this data daily or sorting through what is valid or not valid is cumbersome. Additionally, with the addon "Missing Movies", this episode data also appears there as not matched up in the library.

I have understanding that 1Channel pulls what PW has on its site and what they have is what they have. I am just asking if there is a way to only pull what is matched (ie valid, regular episode data) or a way to have it not pull it again if it is deleted? I ask here as it is an issue with both MediaElch and the Missing Movies addon, and the source of the issue points to library data that 1Channel is pulling. Please note that I do know why it is pulling, so I am not indicating that this is an "error".

**Comment by tknorris** [comment]
No, there's no way. Even if you delete them, they'll come right back on the next sub update. Note that sometimes there is an episode 102. Many shows that air five days a week frequently get up in the 3 digit episode count per season.

**Comment by thwaller** [comment]
Thanks. Yes I am aware of that. I should have been more specific... the series in question goes from 1-10, then 101-120. This is what was meant by obviously there is no 102. Thanks for pointing out the misrepresenting statement, I did not express the situation correctly. Cheers!
